import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import {
  cookieHeaderFromPaste,
  filterCookieJar,
  hasSessionCookie,
  jarFromHeader,
} from '../dist/accounts/cookie-jar.js';

/** Netscape format: domain, includeSubdomains, path, secure, expiry, name, value. */
function line(domain: string, name: string, value = 'v', httpOnly = false): string {
  const body = [domain, 'TRUE', '/', 'TRUE', '1800000000', name, value].join('\t');
  return httpOnly ? `#HttpOnly_${body}` : body;
}

const browserExport = Buffer.from(
  [
    '# Netscape HTTP Cookie File',
    '# This file was generated by a browser extension',
    '',
    line('.youtube.com', '__Secure-3PSID', 'session', true),
    line('.youtube.com', 'PREF'),
    line('.google.com', 'SAPISID'),
    line('accounts.google.com', 'ACCOUNT_CHOOSER'),
    line('.googlevideo.com', 'VISITOR_INFO1_LIVE'),
    // The reason this filter exists at all.
    line('.mybank.example', 'SESSIONID', 'do-not-store'),
    line('.stripe.com', '__stripe_mid'),
    line('.internal-sso.example', 'SAML_TOKEN'),
  ].join('\n'),
  'utf8',
);

describe('filterCookieJar', () => {
  const result = filterCookieJar(browserExport);

  it('keeps only google and youtube domains', () => {
    assert.equal(result.kept, 5);
    assert.equal(result.dropped, 3);
    assert.deepEqual(result.domains, [
      '.google.com',
      '.googlevideo.com',
      '.youtube.com',
      'accounts.google.com',
    ]);
  });

  it('leaves no trace of an unrelated domain in the stored jar', () => {
    // A jar is written to disk for yt-dlp on every download; anything that
    // survives this filter is a credential this app has taken responsibility
    // for holding.
    const jar = result.jar.toString('utf8');
    for (const secret of ['mybank', 'stripe', 'internal-sso', 'do-not-store', 'SAML_TOKEN']) {
      assert.ok(!jar.includes(secret), `${secret} survived the filter`);
    }
  });

  it('preserves the HttpOnly marker yt-dlp expects', () => {
    assert.ok(result.jar.toString('utf8').includes('#HttpOnly_.youtube.com\t'));
  });

  it('writes a jar yt-dlp will parse, and one this app will re-accept', () => {
    assert.ok(result.jar.toString('utf8').startsWith('# Netscape HTTP Cookie File\n'));
    assert.equal(filterCookieJar(result.jar).kept, result.kept);
  });

  it('refuses a jar with no google or youtube cookies', () => {
    const other = Buffer.from(line('.example.com', 'SID'), 'utf8');
    assert.throws(() => filterCookieJar(other), /no youtube.com or google.com cookies/);
  });

  it('refuses a jar with the right domains but no session', () => {
    // Exporting after logging out yields exactly this: plenty of cookies, none
    // that authenticate. Storing it would look like success and fail later, at
    // the moment a file needs to come back.
    const signedOut = Buffer.from(
      [line('.youtube.com', 'PREF'), line('.google.com', 'NID')].join('\n'),
      'utf8',
    );
    assert.throws(() => filterCookieJar(signedOut), /no Google session cookie/);
  });
});

describe('hasSessionCookie', () => {
  it('accepts any of the session cookie names', () => {
    for (const name of ['__Secure-3PSID', '__Secure-1PSID', 'SAPISID', 'SID']) {
      assert.equal(hasSessionCookie(Buffer.from(line('.google.com', name))), true);
    }
  });

  it('sees a session cookie behind the HttpOnly prefix', () => {
    assert.equal(
      hasSessionCookie(Buffer.from(line('.youtube.com', '__Secure-3PSID', 'v', true))),
      true,
    );
  });

  it('rejects an empty or session-less jar', () => {
    // withCookies checks this before re-sealing what yt-dlp left behind: a
    // truncated jar written over a working one destroys the credential.
    assert.equal(hasSessionCookie(Buffer.alloc(0)), false);
    assert.equal(hasSessionCookie(Buffer.from('# Netscape HTTP Cookie File\n')), false);
    assert.equal(hasSessionCookie(Buffer.from(line('.youtube.com', 'PREF'))), false);
  });
});

describe('jarFromHeader', () => {
  // What DevTools shows on the `cookie:` line of any youtube.com request. The
  // session names are the point; the rest is there to prove they survive.
  const header =
    'VISITOR_INFO1_LIVE=abc; __Secure-3PSID=g.a000xyz; SAPISID=sapi/value; ' +
    'LOGIN_INFO=AFmmF2s; PREF=tz=Europe.Madrid';

  it('produces a jar the filter accepts and the session check passes', () => {
    const jar = jarFromHeader(header);

    assert.equal(hasSessionCookie(jar), true);
    const result = filterCookieJar(jar);
    assert.equal(result.kept, 5);
    assert.equal(result.dropped, 0);
    assert.deepEqual(result.domains, ['.youtube.com']);
  });

  it('keeps values containing = and marks every cookie HttpOnly', () => {
    // `PREF` carries `tz=Europe.Madrid`, so splitting on every = would truncate
    // it. Only the first separates name from value.
    const text = jarFromHeader(header).toString('utf8');

    assert.match(text, /#HttpOnly_\.youtube\.com\tTRUE\t\/\tTRUE\t\d+\tPREF\ttz=Europe\.Madrid/);
    assert.equal(text.split('\n').filter((l) => l.startsWith('#HttpOnly_')).length, 5);
  });

  it('honours a different host, since one jar may never mix the two', () => {
    // .google.com and .youtube.com both define SID with different values, and a
    // jar carrying both is answered with CookieMismatch.
    assert.match(jarFromHeader('SID=one', '.google.com').toString('utf8'), /\.google\.com/);
  });

  it('refuses something that is not a cookie header', () => {
    assert.throws(() => jarFromHeader('   '), /does not look like a cookie header/);
    assert.throws(() => jarFromHeader('just some words'), /does not look like a cookie header/);
  });

  it('leaves a session-less header to be rejected by the filter', () => {
    // Pasting from a signed-out tab is the likely mistake, and it has to fail
    // loudly rather than store a jar that authenticates nothing.
    const jar = jarFromHeader('VISITOR_INFO1_LIVE=abc; PREF=tz=Europe.Madrid');
    assert.equal(hasSessionCookie(jar), false);
    assert.throws(() => filterCookieJar(jar), /no Google session cookie/);
  });
});

describe('cookieHeaderFromPaste', () => {
  const cookies = "__Secure-3PSID=g.a000xyz; SAPISID=sapi/value; PREF=tz=Europe.Madrid";

  it('reads the cookies and the URL out of a Chromium "Copy as cURL"', () => {
    // What Chrome, Brave and Edge put on the clipboard: cookies behind -b, the
    // URL first, and a pile of headers that are none of our business.
    const curl =
      `curl 'https://www.youtube.com/' \\\n  -H 'accept: text/html' \\\n` +
      `  -b '${cookies}' \\\n  -H 'user-agent: Mozilla/5.0'`;

    const paste = cookieHeaderFromPaste(curl);
    assert.equal(paste.header, cookies);
    assert.equal(paste.url, 'https://www.youtube.com/');
  });

  it('reads them from -H cookie, which is what Firefox and Safari write', () => {
    const curl = `curl 'https://www.youtube.com/watch?v=abc' -H 'Cookie: ${cookies}'`;

    const paste = cookieHeaderFromPaste(curl);
    assert.equal(paste.header, cookies);
    assert.equal(paste.url, 'https://www.youtube.com/watch?v=abc');
  });

  it("unwraps Chromium's $'…' quoting without truncating the value", () => {
    // Chromium switches to $'…' when a value needs escaping. Treating it as a
    // plain quoted string eats the first character and the cookie silently
    // stops working.
    const paste = cookieHeaderFromPaste(`curl 'https://www.youtube.com/' -b $'SID=one; HSID=two'`);
    assert.equal(paste.header, 'SID=one; HSID=two');
  });

  it('keeps the host of a request that was copied by mistake', () => {
    // A gstatic row carries no YouTube cookies at all, which is why its cURL
    // has no -b. The caller names the host rather than saying "not a header".
    const paste = cookieHeaderFromPaste(
      `curl 'https://www.gstatic.com/cv/js/sender/v1/cast_sender.js' -H 'accept: */*'`,
    );
    assert.equal(paste.header, '');
    assert.equal(paste.url, 'https://www.gstatic.com/cv/js/sender/v1/cast_sender.js');
  });

  it('accepts the header on its own, with or without its name', () => {
    assert.deepEqual(cookieHeaderFromPaste(`cookie: ${cookies}`), { header: cookies, url: null });
    assert.deepEqual(cookieHeaderFromPaste(`  ${cookies}  `), { header: cookies, url: null });
  });

  it('feeds jarFromHeader, which is what the whole paste is for', () => {
    const { header } = cookieHeaderFromPaste(`curl 'https://www.youtube.com/' -b '${cookies}'`);
    assert.equal(hasSessionCookie(jarFromHeader(header)), true);
  });
});
