import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { filterCookieJar, hasSessionCookie } from '../dist/accounts/cookie-jar.js';

/** Netscape format: domain, includeSubdomains, path, secure, expiry, name, value. */
function line(domain: string, name: string, value = 'v', httpOnly = false): string {
  const body = [domain, 'TRUE', '/', 'TRUE', '1800000000', name, value].join('\t');
  return httpOnly ? `#HttpOnly_${body}` : body;
}

const browserExport = Buffer.from(
  [
    '# Netscape HTTP Cookie File',
    '# This file was generated by a browser extension',
    '',
    line('.youtube.com', '__Secure-3PSID', 'session', true),
    line('.youtube.com', 'PREF'),
    line('.google.com', 'SAPISID'),
    line('accounts.google.com', 'ACCOUNT_CHOOSER'),
    line('.googlevideo.com', 'VISITOR_INFO1_LIVE'),
    // The reason this filter exists at all.
    line('.mybank.example', 'SESSIONID', 'do-not-store'),
    line('.stripe.com', '__stripe_mid'),
    line('.internal-sso.example', 'SAML_TOKEN'),
  ].join('\n'),
  'utf8',
);

describe('filterCookieJar', () => {
  const result = filterCookieJar(browserExport);

  it('keeps only google and youtube domains', () => {
    assert.equal(result.kept, 5);
    assert.equal(result.dropped, 3);
    assert.deepEqual(result.domains, [
      '.google.com',
      '.googlevideo.com',
      '.youtube.com',
      'accounts.google.com',
    ]);
  });

  it('leaves no trace of an unrelated domain in the stored jar', () => {
    // A jar is written to disk for yt-dlp on every download; anything that
    // survives this filter is a credential this app has taken responsibility
    // for holding.
    const jar = result.jar.toString('utf8');
    for (const secret of ['mybank', 'stripe', 'internal-sso', 'do-not-store', 'SAML_TOKEN']) {
      assert.ok(!jar.includes(secret), `${secret} survived the filter`);
    }
  });

  it('preserves the HttpOnly marker yt-dlp expects', () => {
    assert.ok(result.jar.toString('utf8').includes('#HttpOnly_.youtube.com\t'));
  });

  it('writes a jar yt-dlp will parse, and one this app will re-accept', () => {
    assert.ok(result.jar.toString('utf8').startsWith('# Netscape HTTP Cookie File\n'));
    assert.equal(filterCookieJar(result.jar).kept, result.kept);
  });

  it('refuses a jar with no google or youtube cookies', () => {
    const other = Buffer.from(line('.example.com', 'SID'), 'utf8');
    assert.throws(() => filterCookieJar(other), /no youtube.com or google.com cookies/);
  });

  it('refuses a jar with the right domains but no session', () => {
    // Exporting after logging out yields exactly this: plenty of cookies, none
    // that authenticate. Storing it would look like success and fail later, at
    // the moment a file needs to come back.
    const signedOut = Buffer.from(
      [line('.youtube.com', 'PREF'), line('.google.com', 'NID')].join('\n'),
      'utf8',
    );
    assert.throws(() => filterCookieJar(signedOut), /no Google session cookie/);
  });
});

describe('hasSessionCookie', () => {
  it('accepts any of the session cookie names', () => {
    for (const name of ['__Secure-3PSID', '__Secure-1PSID', 'SAPISID', 'SID']) {
      assert.equal(hasSessionCookie(Buffer.from(line('.google.com', name))), true);
    }
  });

  it('sees a session cookie behind the HttpOnly prefix', () => {
    assert.equal(
      hasSessionCookie(Buffer.from(line('.youtube.com', '__Secure-3PSID', 'v', true))),
      true,
    );
  });

  it('rejects an empty or session-less jar', () => {
    // withCookies checks this before re-sealing what yt-dlp left behind: a
    // truncated jar written over a working one destroys the credential.
    assert.equal(hasSessionCookie(Buffer.alloc(0)), false);
    assert.equal(hasSessionCookie(Buffer.from('# Netscape HTTP Cookie File\n')), false);
    assert.equal(hasSessionCookie(Buffer.from(line('.youtube.com', 'PREF'))), false);
  });
});
